# Generated by Django 5.2.4 on 2025-07-23 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(help_text='ID канала в Telegram'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('owner', 'channel_id')},
        ),
    ]
