# Generated by Django 5.2.4 on 2025-07-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channel_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='balance',
            field=models.IntegerField(default=5, help_text='Баланс для заданий'),
        ),
    ]
